apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-quarkus
  labels:
    app: hello-quarkus
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-quarkus
  template:
    metadata:
      labels:
        app: hello-quarkus
    spec:
      containers:
      - name: hello-quarkus
        image: 679045741204.dkr.ecr.us-east-1.amazonaws.com/hello-quarkus:3.2
        ports:
        - containerPort: 8080
        # Resource limits for Native Image are much lower than standard Java
        resources:
          limits:
            cpu: "500m"
            memory: "128Mi"
          requests:
            cpu: "100m"
            memory: "64Mi"
        # Probes ensure EKS doesn't send traffic until the app is live
        startupProbe:
          httpGet:
            path: /hello # Use your main endpoint since we know it works
            port: 8080
          failureThreshold: 30 # Try 30 times
          periodSeconds: 1     # Every 1 second
        # 2. Liveness Probe: Only starts AFTER Startup Probe passes
        livenessProbe:
          httpGet:
            path: /hello
            port: 8080
          periodSeconds: 10
          failureThreshold: 3
        # 3. Readiness Probe: Tells EKS when to send actual user traffic
        readinessProbe:
          httpGet:
            path: /hello
            port: 8080
          initialDelaySeconds: 2
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: hello-quarkus-service
spec:
  type: LoadBalancer # This creates an AWS ELB to give you a public URL
  selector:
    app: hello-quarkus
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080